### ISSUE TITLE
Standard vim load-protection

### ISSUE THREAD

**Issue by ohpauleez** [jebberjeb/clojure-socketrepl.nvim#2]
First and foremost -- thanks!  This is an improvement over my pane/window-split hack.

I share plugins between neovim and standard vim.  It would be nice if there was a simple protection around autoloading.  For example, this does the trick:

```
if !exists('g:manually_start_socket_repl_plugin')
    if has("nvim")
        call StartIfNotRunning()
    endif
endif
```

**Comment by jebberjeb** [comment]
Thanks @ohpauleez, I added it on master 5497e8ac8793f5a4b589df4dac61405726c2aa17. 

Lots of rough edges still, any other input would be very welcomed.
