### ISSUE TITLE
nREPL: unexpected type uin bencode data^@

### ISSUE THREAD

**Issue by tomgeorge** [jebberjeb/clojure-socketrepl.nvim#3]
Hi, 

First of all, this is super cool! Thanks for making it :smiley: 

I was trying to run your tmux dev script and was unable to connect to the socket repl on 5555.  

## Steps to reproduce:

1. `git clone https://github.com/jebberjeb/clojure-socketrepl.nvim`
2. Add `jebberjeb/clojure-socketrepl.nvim` to `init.vim` and run `:PluginInstall`
3. `cd clojure-socketrepl.nvim `
4. `lein classpath`
5. `./tmux-run-dev-self.sh`

In the new tmux pane that was created, switch to the neovim window, and `:Connect`
+ `Protocol: nREPL`
+ `Host: localhost`
+ `Port: 5555`

This then comes back with 
`nREPL  unexpected type uin bencode data^@`

## Nvim built from revision: 
10c3b206cbf394d7b67bff95242b7033a1ce1d63

## `uname -a`
Linux vagrant-ubuntu-trusty-64 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## `cat /etc/*-release`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

## `tmux -V`
tmux 1.8

**Comment by tomgeorge** [comment]
I had to uninstall fireplace to get the Connect to work

**Comment by jebberjeb** [comment]
@tomgeorge so you got it working? Glad to hear it.
